# Copyright (C) 2018 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 1

comments:
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

complexity:
  MethodOverloading:
    active: true

exceptions:
  NotImplementedDeclaration:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

formatting:
  EnumEntryNameCase:
    active: true
  SpacingAroundDoubleColon:
    active: true

naming:
  NonBooleanPropertyPrefixedWithIs:
    active: true
    excludes: ['**/test/**']

potential-bugs:
  Deprecation:
    active: true
  HasPlatformType:
    active: true
  IgnoredReturnValue:
    active: true
  ImplicitDefaultLocale:
    active: true
  LateinitUsage:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  NullableToStringCall:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: true

style:
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
  ForbiddenMethodCall:
    active: true
    methods:
      - kotlin.io.println
      - kotlin.io.print
  LibraryEntitiesShouldNotBePublic:
    active: true
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  NestedClassesVisibility:
    active: true
  NoTabs:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    max: 4
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedPrivateMember:
    active: true
  UseArrayLiteralsInAnnotations:
    active: true
  UseCheckOrError:
    active: true
  UseDataClass:
    active: true
  UseCheckNotNull:
    active: true
  UseEmptyCounterpart:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseRequire:
    active: true
  UseRequireNotNull:
    active: true
